import { Books } from "../model";

export const isValidISBN = async (isbn: string) => {
  let sum = 0;

  for (let i = 0; i < isbn.length - 1; i++) {
    sum += (i + 1) * parseInt(isbn[i]);
  }

  sum +=
    isbn[isbn.length - 1] === "X"
      ? 10 * 10
      : 10 * parseInt(isbn[isbn.length - 1]);

  return sum % 11 === 0;
};

export const books: Books[] = [
  {
    isbn: "1781106460",
    Title: "Harry Potter: The Complete Collection (1-7)",
    Authors: "J.K. Rowling",
    Genre: "Young Adult Fiction",
    Height: 4236,
    Publisher: "Pottermore Publishing",
  },
  {
    isbn: "1781659230",
    Title: "The Hogwarts Library Collection",
    Authors: "J.K. Rowling",
    Genre: "Fiction",
    Height: 350,
    Publisher: "Pottermore Publishing",
  },
  {
    isbn: "0549290352",
    Title: "Harry Potter and the Sorcerer's Stone",
    Authors: "J. K. Rowling",
    Genre: "Juvenile Fiction",
    Height: 256,
    Publisher: "Arthur A. Levine Books",
  },
  {
    isbn: "0883115491",
    Title: "The Ivory Tower and Harry Potter",
    Authors: "Lana A. Whited",
    Genre: "Literary Criticism",
    Height: 418,
    Publisher: "Arthur A. Levine Books",
  },
  {
    isbn: "0709639598",
    Title: "Harry Potter and International Relations",
    Authors: "Daniel H. Nexon",
    Genre: "Literary Criticism",
    Height: 245,
    Publisher: "Rowman & Littlefield",
  },
  {
    isbn: "0313320675",
    Title: "Reading Harry Potter",
    Authors: "David G. Epstein",
    Genre: "Literary Criticism",
    Height: 217,
    Publisher: "Greenwood Publishing Group",
  },
  {
    isbn: "0874594107",
    Title: "Harry Potter",
    Authors: "S. Gunelius",
    Genre: "Business & Economics",
    Height: 194,
    Publisher: "Springer",
  },
  {
    isbn: "1935251376",
    Title: "The Psychology of Harry Potter",
    Authors: "Neil Mulholland",
    Genre: "Psychology",
    Height: 326,
    Publisher: "BenBella Books, Inc.",
  },
  {
    isbn: "133741291X",
    Title: "Harry Potter",
    Authors: "J. K. Rowling",
    Genre: "Juvenile Fiction",
    Height: " No Height",
    Publisher: "Springer",
  },
  {
    isbn: "0615172822",
    Title: "The Magic of Harry Potter",
    Authors: "Daniel Mitchell",
    Genre: "Fiction",
    Height: 108,
    Publisher: "Lulu.com",
  },
  {
    isbn: "1409478416",
    Title: "Heroism in the Harry Potter Series",
    Authors: "Dr Katrin Berndt",
    Genre: "Literary Criticism",
    Height: 248,
    Publisher: "Ashgate Publishing, Ltd.",
  },
  {
    isbn: "0826453171",
    Title: "Guide to the Harry Potter Novels",
    Authors: "Julia Eccleshare",
    Genre: "Literary Criticism",
    Height: 114,
    Publisher: "A&C Black",
  },
  {
    isbn: "1589395824",
    Title: "The Harry Potter Companion",
    Authors: "Acascias Riphouse",
    Genre: "Literary Criticism",
    Height: 537,
    Publisher: "Virtualbookworm Publishing",
  },
  {
    isbn: "074753779X",
    Title: "Females and Harry Potter",
    Authors: "Ruthann Mayes-Elma",
    Genre: "Literary Criticism",
    Height: 155,
    Publisher: "Rowman & Littlefield",
  },
  {
    isbn: "1858546661",
    Title: "The Irresistible Rise of Harry Potter",
    Authors: "Andrew Blake",
    Genre: "Literary Criticism",
    Height: 118,
    Publisher: "Pottermore Publishing",
  },
  {
    isbn: "1440650993",
    Title: "The Science of Harry Potter",
    Authors: "Roger Highfield",
    Genre: "Literary Criticism",
    Height: 368,
    Publisher: "Penguin",
  },
  {
    isbn: "1234512345",
    Title: "Harry Potter and the Deathy Hallows Summary & Study Guide |",
    Authors: "BookRags",
    Genre: "No Genre",
    Height: " No Height",
    Publisher: "BookRags",
  },
  {
    isbn: "0664236588",
    Title: "The Gospel According to Harry Potter",
    Authors: "Connie Neal",
    Genre: "Religion",
    Height: 305,
    Publisher: "Westminster John Knox Press",
  },
  {
    isbn: "0664226698",
    Title: "The Gospel According to Harry Potter",
    Authors: "Connie W. Neal",
    Genre: "Religion",
    Height: 69,
    Publisher: "Westminster John Knox Press",
  },
  {
    isbn: "0715188266",
    Title: "Mixing it Up With-- Harry Potter",
    Authors: "Owen Smith",
    Genre: "Church work with youth",
    Height: 35,
    Publisher: "Verso",
  },
  {
    isbn: "1569757119",
    Title: "Mugglenet.com's Harry Potter Should Have Died",
    Authors: "Emerson Spartz",
    Genre: "Juvenile Nonfiction",
    Height: 205,
    Publisher: "Ulysses Press",
  },
  {
    isbn: "159800221X",
    Title: "Friends and Foes of Harry Potter",
    Authors: "Nikita Agarwal",
    Genre: "Juvenile Nonfiction",
    Height: 159,
    Publisher: "Texas World Publishing",
  },
  {
    isbn: "0830832882",
    Title: "A Parent's Guide to Harry Potter",
    Authors: "Gina Burkart",
    Genre: "Family & Relationships",
    Height: 112,
    Publisher: "InterVarsity Press",
  },
  {
    isbn: "1450745601",
    Title: "The Ultimate Guide to the Harry Potter Fandom",
    Authors: "No Authors",
    Genre: "Fans (Persons)",
    Height: 310,
    Publisher: "What The Flux Comics Publis",
  },
  {
    isbn: "1101133139",
    Title: "Harry Potter's Bookshelf",
    Authors: "John Granger",
    Genre: "Social Science",
    Height: 336,
    Publisher: "Penguin",
  },
  {
    isbn: "0812694554",
    Title: "Harry Potter and Philosophy",
    Authors: "David Baggett",
    Genre: "Fiction",
    Height: 243,
    Publisher: "Open Court Publishing",
  },
  {
    isbn: "1576906388",
    Title:
      "A Guide for Using Harry Potter and the Sorcerer's Stone/Other Harry Potter Books in the Classroom",
    Authors: "Michelle Breyer",
    Genre: "Activity programs in education",
    Height: 48,
    Publisher: "Teacher Created Resources",
  },
  {
    isbn: "17866700519",
    Title: "Harry Potter and the Prisoner of Azkaban",
    Authors: "J.K. Rowling",
    Genre: "Fiction",
    Height: 448,
    Publisher: "Verso",
  },
  {
    isbn: "0826452329",
    Title: "JK Rowling's Harry Potter Novels",
    Authors: "Philip Nel",
    Genre: "Literary Criticism",
    Height: 96,
    Publisher: "A&C Black",
  },
  {
    isbn: "1937520986",
    Title: "Harry Potter Places",
    Authors: "C. D. Miller",
    Genre: "Fiction",
    Height: 156,
    Publisher: "First Edition Design Pub.",
  },
  {
    isbn: "UVA:X004831592",
    Title: "Harry Potter",
    Authors: "No Authors",
    Genre: "No Genre",
    Height: " No Height",
    Publisher: "Verso",
  },
  {
    isbn: "0576516803",
    Title: "The End of Harry Potter?",
    Authors: "David Langford",
    Genre: "Fiction",
    Height: 208,
    Publisher: "Hachette UK",
  },
  {
    isbn: "1458154041",
    Title: "Essays on Harry Potter",
    Authors: "Leann Richards",
    Genre: "No Genre",
    Height: " No Height",
    Publisher: "Leann Richards",
  },
  {
    isbn: "1421410346",
    Title: "Harry Potter and the Millennials",
    Authors: "Anthony Gierzynski",
    Genre: "Political Science",
    Height: 136,
    Publisher: "JHU Press",
  },
  {
    isbn: "1788630500",
    Title: "Harry Potter and the Chamber of Secrets",
    Authors: "J.K. Rowling",
    Genre: "Fiction",
    Height: 341,
    Publisher: "Pottermore Publishing",
  },
  {
    isbn: "1135891540",
    Title: "Critical Perspectives on Harry Potter",
    Authors: "Elizabeth E. Heilman",
    Genre: "Education",
    Height: 368,
    Publisher: "Routledge",
  },
  {
    isbn: "0230935578",
    Title: "The Riddles of Harry Potter",
    Authors: "Shira Wolosky",
    Genre: "Fiction",
    Height: 225,
    Publisher: "Springer",
  },
  {
    isbn: "075766536X",
    Title: "Harry Potter and the Cursed Child",
    Authors: "J. K. Rowling",
    Genre: "Fiction",
    Height: 352,
    Publisher: "Springer",
  },
  {
    isbn: "1476601224",
    Title: "Teaching with Harry Potter",
    Authors: "Valerie Estelle Frankel",
    Genre: "Literary Criticism",
    Height: 288,
    Publisher: "McFarland",
  },
  {
    isbn: "1934840440",
    Title: "The Unauthorized Harry Potter Quiz Book",
    Authors: "Graeme Davis",
    Genre: "Juvenile Nonfiction",
    Height: 76,
    Publisher: "Nimble Books LLC",
  },
];
